research_task:
  description: >
    Conduct exhaustive research on {topic} and its subtopics.
    Make sure to find any interesting and relevant information given
    that the current year is {current_year}.
  expected_output: >
    A list of all the necessary and highlighted points of the
    most relevant information about {topic} and its subtopics.
  agent: researcher

# youtube_research_task:
#   description: >
#     Search for information on {topic} in the video with the link {youtube_video_url}

#     Focus on:
#     1. Key points mentioned in the video.
#     2. Real-world applications of what is mentioned in the video.
#     3. Possible improvements that could be made to the content.

#     Generate a useful summary of the content.
#   expected_output: >
#     A detailed and useful summary of the video's content.
#   agent: youtube_video_researcher

screenwriting_task:
  description: >
    Review the obtained context and also look for the structure of the script in the
    path {file_path} within the base script you will use as a reference, remember to
    use the {file_path} as a parameter of the `@DOCXReadTool` too. Pay particular attention
    to the tone and structure of that script to create a similar one using the
    new context. Write a script in a {tones} tone, as only you know how, based on that information
    and the previous script.
    Use the `@notion_tool_langgraph()` to create a page and save
    the title and content of the script when this is completely finished.
  expected_output: >
    An engaging, interesting, fun, and educational script for a YouTube video
    written in a {tones} tone. Return the video title and the content formatted as markdown without '```'.
  agent: screenwriter
